spring.application.name=HN-K24-CNTT3_LeThanhTung_004
#Config datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hackathon_ss14?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

#Config jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Config pagination
pageSizeProducts = 3

#Config logging
#logging.file.name=logs/application.log
#logging.pattern.console=%d{yyyy-MM-dd hh:mm:ss.SSS} - %-5level - %logger{50} - %msg%n
#logging.logback.rollingpolicy.max-file-size=50MB
#logging.logback.rollingpolicy.max-history=30
#logging.level.root=INFO
#logging.level.ra.demo.repository=WARN
#logging.level.ra.demo.service=WARN
#logging.level.org.springframework=WARN
#logging.level.sql=WARN
#logging.level.org.hibernate=WARN